name: 'id-analyzer-action'
description: 'Analyze the quality of your identifiers'
author: 'Remo Gresta'
inputs:
  repoName:
    required: true
    description: 'name of the repository'
  onwer:
    required: true
    description: 'owner of the repository'
  branch:
    required: false
    description: 'branch of the repository'
    default: 'master'

runs:
  using: 'node16'
  main: 'dist/index.js'
